[build]
  command = "npm run build"
  publish = "dist"

# Proxy API trên production để tránh CORS
[[redirects]]
  from = "/api/*"
  to = "http://203.209.181.170:2018/:splat"
  status = 200
  force = true

# (Tuỳ chọn) SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
